# Generated by Django 3.0.3 on 2020-04-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='website',
            field=models.URLField(max_length=255),
        ),
    ]
