# Generated by Django 3.1.5 on 2021-10-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20211011_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='minimum_bid',
            field=models.IntegerField(),
        ),
    ]
