# Generated by Django 3.2.9 on 2021-11-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_biddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddate',
            name='minimum_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biddate',
            name='product',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
