# Generated by Django 3.0.3 on 2020-05-31 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('happy_customers', models.CharField(max_length=100)),
                ('branches', models.CharField(max_length=100)),
                ('partners', models.CharField(max_length=100)),
                ('awards', models.CharField(max_length=100)),
                ('updated_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
