# Generated by Django 3.1.5 on 2021-02-12 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name_plural': 'About Us'},
        ),
    ]
