# Generated by Django 3.0.3 on 2020-02-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='cart.CartItem'),
        ),
    ]
