# Generated by Django 3.0.3 on 2020-05-23 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20200523_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
