# Generated by Django 3.0.3 on 2020-02-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=255, max_length=255, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=255, max_length=255, null=True)),
                ('status', models.ImageField(choices=[(0, 'Draft'), (1, 'Publish')], upload_to='')),
            ],
        ),
    ]
