# Generated by Django 3.0.3 on 2020-02-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('fastfood', 'FastFood'), ('healthyfood', 'HealthyFood'), ('fruits', 'Fruits'), ('Juice', 'Juice'), ('vegitables', 'Vegitables')], max_length=255, null=True),
        ),
    ]
