# Generated by Django 3.0.3 on 2020-02-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200221_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('fastfood', 'FastFood'), ('healthyfood', 'HealthyFood'), ('fruit', 'Fruit'), ('Juice', 'Juice'), ('vegitable', 'Vegitable')], max_length=255, null=True),
        ),
    ]
