# Generated by Django 3.0.3 on 2020-03-28 13:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='updateon',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 16, 27, 10, 475240)),
        ),
        migrations.CreateModel(
            name='wishlist_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('updateon', models.DateTimeField(default=datetime.datetime(2020, 3, 28, 16, 27, 10, 476239))),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('listed_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Wishlist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(related_name='items', to='products.wishlist_item'),
        ),
    ]
