# Generated by Django 3.0.3 on 2020-03-28 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200328_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items', to='products.wishlist_item'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='updateon',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 16, 39, 18, 69682)),
        ),
        migrations.AlterField(
            model_name='wishlist_item',
            name='listed_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Wishlist'),
        ),
        migrations.AlterField(
            model_name='wishlist_item',
            name='updateon',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 16, 39, 18, 70713)),
        ),
    ]
