# Generated by Django 3.1.5 on 2021-02-12 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20200531_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('fastfood', 'FastFood'), ('dried', 'Dried'), ('fruit', 'Fruit'), ('juice', 'Juice'), ('vegitable', 'Vegitable')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='updateon',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 1, 18, 57, 848991)),
        ),
        migrations.AlterField(
            model_name='wishlist_item',
            name='updateon',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 1, 18, 57, 850037)),
        ),
    ]
