# Generated by Django 3.1.5 on 2021-10-11 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20211011_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='updateon',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 14, 31, 8, 56610)),
        ),
        migrations.AlterField(
            model_name='wishlist_item',
            name='updateon',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 14, 31, 8, 57881)),
        ),
    ]
