# Generated by Django 3.1.5 on 2021-10-11 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20211011_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='updateon',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 15, 40, 22, 537519)),
        ),
        migrations.AlterField(
            model_name='wishlist_item',
            name='updateon',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 15, 40, 22, 538708)),
        ),
    ]
