# Generated by Django 3.2.9 on 2021-11-19 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20211012_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='updateon',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 11, 22, 43, 543995)),
        ),
        migrations.AlterField(
            model_name='wishlist_item',
            name='updateon',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 11, 22, 43, 545229)),
        ),
    ]
