# Generated by Django 3.2.9 on 2021-11-19 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20211119_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='updateon',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 11, 38, 59, 866476)),
        ),
        migrations.AlterField(
            model_name='wishlist_item',
            name='updateon',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 11, 38, 59, 867951)),
        ),
    ]
